"use client";

import { useEffect, useState } from "react";
import { fetchSignalDetail, fetchSignalQueue } from "@/lib/signal/client";
import type { SignalDetail, SignalQueue, SignalRow, SignalType } from "@/lib/signal/schema";
import styles from "@/components/attention/Attention.module.css";

const labels: Record<SignalType, string> = { availability: "Availability Risk", demand_momentum: "Demand Momentum Gap", inventory_imbalance: "Inventory Imbalance Exposure" };
const money = (value: string | null) => value === null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
const number = (value: string) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(Number(value));

export default function SignalView() {
  const [queue, setQueue] = useState<SignalQueue | null>(null);
  const [filter, setFilter] = useState<SignalType | undefined>();
  const [selected, setSelected] = useState<SignalRow | null>(null);
  const [detail, setDetail] = useState<SignalDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); fetchSignalQueue(filter, controller.signal).then((value) => { setQueue(value); setSelected(null); setDetail(null); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "The immutable signal release could not be validated."); }); return () => controller.abort(); }, [filter]);
  useEffect(() => { if (!selected) return; const controller = new AbortController(); fetchSignalDetail(selected.signal_id, controller.signal).then(setDetail).catch(() => { if (!controller.signal.aborted) setError("Signal evidence could not be validated."); }); return () => controller.abort(); }, [selected]);
  if (error) return <section className={styles.loadState}><p className={styles.eyebrow}>Memento Signal</p><h1>Release unavailable</h1><p>{error}</p></section>;
  if (!queue) return <section className={styles.loadState}><p className={styles.eyebrow}>Memento Signal</p><h1>Loading ranked signals</h1></section>;
  return <div className={styles.page}>
    <header className={styles.pageHeader}><div><p className={styles.eyebrow}>Immutable overall top ten</p><h1>Memento Signal</h1></div><div className={styles.runMeta}><span>Cutoff {new Date(queue.run.signal_as_of).toLocaleString("en-US", { timeZone: "UTC", timeZoneName: "short" })}</span><span>{queue.run.metric_contract_version}</span></div></header>
    <section className={styles.summary} aria-label="Signal run summary"><Summary label="Eligible signals" value={String(queue.run.candidate_count)} /><Summary label="Displayed overall top ten" value={String(queue.run.display_count)} /><Summary label="Availability" value={String(queue.run.candidate_counts_by_type.availability)} /><Summary label="Demand momentum" value={String(queue.run.candidate_counts_by_type.demand_momentum)} /><Summary label="Inventory imbalance" value={String(queue.run.candidate_counts_by_type.inventory_imbalance)} /></section>
    <div className={styles.legend} aria-label="Signal type filter"><button aria-pressed={!filter} onClick={() => setFilter(undefined)}>All types</button>{(Object.keys(labels) as SignalType[]).map((type) => <button key={type} aria-pressed={filter === type} onClick={() => setFilter(type)}>{labels[type]}</button>)}</div>
    <div className={styles.workspace}><section className={styles.panel}><div className={styles.panelHeader}><div><p className={styles.eyebrow}>Ranked queue</p><h2>Signals retain overall rank when filtered</h2></div></div><div className={styles.definitionList}>{queue.signals.map((signal) => <button key={signal.signal_id} onClick={() => { setSelected(signal); setDetail(null); }} style={{ textAlign: "left", padding: "1rem", border: "1px solid #ddd", background: selected?.signal_id === signal.signal_id ? "#eef5ff" : "white" }}><strong>#{signal.overall_rank_position} · {labels[signal.signal_type]}</strong><br />{signal.identity.store_name} · {signal.identity.item_name}<br /><span>{signal.signal_direction} · type rank #{signal.signal_type_rank_position} · {number(signal.headline_metric_value)} {signal.headline_metric_name.replaceAll("_", " ")}</span></button>)}</div></section>
      <aside className={styles.aside}>{selected ? <SignalCard signal={selected} detail={detail} /> : <div className={styles.hint}>Select a ranked signal to inspect its native economics, confidence components, and type-specific evidence.</div>}</aside></div>
  </div>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }

function SignalCard({ signal, detail }: { signal: SignalRow; detail: SignalDetail | null }) {
  return <article className={styles.card}><p className={styles.eyebrow}>Overall #{signal.overall_rank_position} · Type #{signal.signal_type_rank_position}</p><h2>{labels[signal.signal_type]}</h2><p>{signal.identity.item_name} at {signal.identity.store_name}</p><div className={styles.cardFacts}><Fact label="Revenue opportunity / exposure" value={money(signal.estimated_retail_sales_impact_amount)} /><Fact label="Contribution impact" value={money(signal.estimated_contribution_impact_amount)} /><Fact label="Inventory capital exposed" value={money(signal.inventory_cost_exposed_amount)} /><Fact label="28-day carrying cost" value={money(signal.carrying_cost_28d_amount)} /><Fact label="Material impact" value={`${signal.days_until_material_impact} days`} /><Fact label="Reaction slack" value={`${signal.action_slack_days} days`} /></div><p className={styles.mutedCopy}>Economic basis: {signal.economic_impact_basis.replaceAll("_", " ")}. Confidence is an evidence-quality score, not a probability.</p>{detail ? <><h3>{signal.signal_type === "demand_momentum" ? "Weekly and forward demand evidence" : "Low, base, and high inventory evidence"}</h3><p>{detail.evidence.length} published rows · forecast quality {number(detail.signal.forecast_quality)} · completeness {number(detail.signal.data_completeness)} · stability {number(detail.signal.stability_score)}</p><dl className={styles.definitionList}>{detail.evidence.slice(0, 8).map((row, index) => <div key={`${row.evidence_date}-${row.path ?? row.evidence_type}-${index}`}><dt>{row.evidence_date} · {row.path ?? row.evidence_type.replaceAll("_", " ")}</dt><dd>{row.evidence_type === "historical_week" ? `Actual ${number(row.actual_units ?? "0")} · retailer ${number(row.retailer_forecast_units ?? "0")}` : row.evidence_type === "forward_demand" ? `Retailer ${number(row.retailer_forecast_units ?? "0")} · adjusted ${number(row.adjusted_forecast_units ?? "0")}` : `Ending ${number(row.ending_units ?? "0")} · target ${row.target_units === null ? "—" : number(row.target_units)}`}</dd></div>)}</dl><div className={styles.lineage}><div><strong>Source release</strong><span>{detail.signal.source_release_set_id}</span></div><div><strong>Publication</strong><span>{detail.signal.signal_publication_version}</span></div><div><strong>Ranker</strong><span>{detail.signal.ranker_version}</span></div></div></> : <p>Validating evidence…</p>}</article>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className={styles.fact}><span>{label}</span><strong>{value}</strong></div>; }
